;+>         SciTEDir => C:\Program Files\AutoIt3\SciTE   UserDir => C:\Users\user\AppData\Local\AutoIt v3\SciTE\AutoIt3Wrapper   SCITE_USERHOME => C:\Users\user\AppData\Local\AutoIt v3\SciTE
;#region --- Au3Recorder generated code Start (v3.3.9.5 KeyboardLayout=00000411)  ---

#region --- Internal functions Au3Recorder Start ---
Func _Au3RecordSetup()
Opt('WinWaitDelay',350)
Opt('WinDetectHiddenText',1)
Opt('MouseCoordMode',0)
Opt("MouseClickDelay",250)
Opt("SendKeyDelay",100)
Opt("WinSearchChildren", 1)
Local $aResult = DllCall('User32.dll', 'int', 'GetKeyboardLayoutNameW', 'wstr', '')
If $aResult[1] <> '00000411' Then
  _MsgBox(64, 'Warning', 'Recording has been done under a different Keyboard layout' & @CRLF & '(00000411->' & $aResult[1] & ')')
EndIf

EndFunc

Func _WinWaitActivate($title,$text,$timeout=0)
	WinWait($title,$text,$timeout)
	If Not WinActive($title,$text) Then WinActivate($title,$text)
	WinWaitActive($title,$text,$timeout)
EndFunc

Func _MsgBox($mode,$title,$text,$timeout=0,$handle=0)
	BlockInput(0)
	MsgBox($mode,$title,$text,$timeout,$handle)
	;BlockInput(1)
EndFunc

;~ Func _MsgBox($mode,$title,$text)
;~ 	BlockInput(0)
;~ 	MsgBox($mode,$title,$text)
;~ 	BlockInput(1)
;~ EndFunc

_AU3RecordSetup()
#endregion --- Internal functions Au3Recorder End ---

_WinWaitActivate("MogiEditor","statusStrip1")
;WinMove("MogiEditor","statusStrip1",184, 46)
Local $dHandle=WinGetHandle("MogiEditor")
_MsgBox(64,"方法","まずは、問題にしたい文字列を選択します",0,$dHandle)
MouseMove(156,75)
MouseDown("left")

MouseMove(183,74)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
$dHandle=WinGetHandle("問題作成")
_MsgBox(64,"方法","すると、このようなダイアログが出るので、OKを押します",0,$dHandle)

MouseMove(152,361)
MouseDown("left")

MouseMove(153,361)
MouseUp("left")
_WinWaitActivate("MogiEditor","statusStrip1")
_MsgBox(64,"方法","これで、穴埋め問題が1問作成できました。")
MouseMove(380,79)
MouseDown("left")
MouseMove(418,77)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
MouseClick("left",168,364,1)
_WinWaitActivate("MogiEditor","statusStrip1")
MouseMove(188,147)
MouseDown("left")
MouseMove(214,150)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
$dHandle=WinGetHandle("問題作成")
_MsgBox(64,"方法","選択問題を作成するには、下部のテキストエリアの各行に" & @CRLF & "1つずつ選択肢を書いていきます",0,$dHandle)
MouseClick("left",141,224,1)
Send("higeki{SPACE}{ENTER}{ENTER}")
Send("omaturi{SPACE}{ENTER}{ENTER}")
Send("gabagaba{ENTER}")
MouseClick("left",360,180,2)
MouseClick("left",360,276,1)
_MsgBox(64,"方法","このように、正解の番号や記号を設定できます。",0,$dHandle)
MouseClick("left",169,361,1)
_WinWaitActivate("MogiEditor","statusStrip1")
$dHandle=WinGetHandle("MogiEditor")
_MsgBox(64,"方法","これで、選択問題が1問作成できました。",0,$dHandle)
MouseClick("left",716,291,1)
_MsgBox(64,"方法","ここをチェックすると記述問題が作成できます。"&@CRLF&"記述問題は解答者が正誤を判断できます。")
MouseMove(204,300)
MouseDown("left")
MouseMove(295,301)
MouseUp("left")
MouseClick("left",691,285,1)
MouseClick("left",700,470,1)
MouseClick("left",693,496,1)
MouseClick("left",779,518,1)
_MsgBox(64,"方法","ここで模擬テストの制限時間を設定できます。",0,$dHandle)
MouseClick("left",747,560,1)
_WinWaitActivate("試験開始!!","模擬テストを始めます。")
MouseClick("left",203,153,1)
_WinWaitActivate("MogiTester","Ctrl＋Enter：前の問題")
Send("seitou{SPACE}{ENTER}{ENTER}")
Send("kokkai{SPACE}{ENTER}{ENTER}")
Send("{DOWN}{DOWN}{ENTER}")
Send("arenihansuru{SPACE}{ENTER}")
Send("{F1}")
_WinWaitActivate("記述問題の採点","")
MouseClick("left",185,218,1)
_WinWaitActivate("採点結果","正解率は")
Send("{LEFT}{ENTER}")
_WinWaitActivate("MogiTester","Ctrl＋Enter：前の問題")
MouseClick("left",988,9,1)
