;+>         SciTEDir => C:\Program Files\AutoIt3\SciTE   UserDir => C:\Users\user\AppData\Local\AutoIt v3\SciTE\AutoIt3Wrapper   SCITE_USERHOME => C:\Users\user\AppData\Local\AutoIt v3\SciTE
#region --- Au3Recorder generated code Start (v3.3.9.5 KeyboardLayout=00000411)  ---

#region --- Internal functions Au3Recorder Start ---
Func _Au3RecordSetup()
Opt('WinWaitDelay',350)
Opt('WinDetectHiddenText',1)
Opt('MouseCoordMode',0)
Local $aResult = DllCall('User32.dll', 'int', 'GetKeyboardLayoutNameW', 'wstr', '')
If $aResult[1] <> '00000411' Then
  MsgBox(64, 'Warning', 'Recording has been done under a different Keyboard layout' & @CRLF & '(00000411->' & $aResult[1] & ')')
EndIf

EndFunc

Func _WinWaitActivate($title,$text,$timeout=0)
	WinWait($title,$text,$timeout)
	If Not WinActive($title,$text) Then WinActivate($title,$text)
	WinWaitActive($title,$text,$timeout)
EndFunc

_AU3RecordSetup()
#endregion --- Internal functions Au3Recorder End ---

_WinWaitActivate("MogiEditor","statusStrip1")
WinMove("MogiEditor","statusStrip1",184, 46)
MsgBox(64,"方法","まずは、問題にしたい文字列を選択します")
MouseMove(156,75)
MouseDown("left")
Sleep(350)
MouseMove(183,74)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
Local $dHandle=WinGetHandle("問題作成")
MsgBox(64,"方法","すると、このようなダイアログが出るので、OKを押します",0,$dHandle)
Sleep(350)
MouseMove(152,361)
MouseDown("left")
Sleep(350)
MouseMove(153,361)
MouseUp("left")
_WinWaitActivate("MogiEditor","statusStrip1")
MsgBox(64,"方法","これで、穴埋め問題が1問作成できました。")
MouseMove(380,79)
MouseDown("left")
Sleep(350)
MouseMove(418,77)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
Sleep(350)
MouseClick("left",168,364,1)
_WinWaitActivate("MogiEditor","statusStrip1")
Sleep(350)
MouseMove(188,147)
MouseDown("left")
Sleep(350)
MouseMove(214,150)
MouseUp("left")
_WinWaitActivate("問題作成","記入欄（選択問題か別解がある穴埋め問題を")
$dHandle=WinGetHandle("問題作成")
MsgBox(64,"方法","選択問題を作成するには、下部のテキストエリアの各行に1つずつ選択肢を書いていきます",0,$dHandle)
Sleep(350)
MouseClick("left",141,224,1)
Send("higeki{SPACE}{ENTER}{ENTER}omaturi{SPACE}{ENTER}{ENTER}gabagaba{ENTER}")
Sleep(350)
MouseClick("left",360,180,2)
Sleep(350)
MouseClick("left",360,276,1)
Sleep(350)
MouseClick("left",169,361,1)
Sleep(350)
MsgBox(64,"方法","このように、正解の番号や記号を設定できます。",0,$dHandle)
_WinWaitActivate("MogiEditor","statusStrip1")
MsgBox(64,"方法","これで、選択問題が1問作成できました。")
MouseClick("left",716,291,1)
MouseMove(204,300)
MouseDown("left")
Sleep(350)
MouseMove(295,301)
MouseUp("left")
Sleep(350)
MouseClick("left",691,285,1)
MouseClick("left",700,470,1)
MouseClick("left",693,496,1)
MouseClick("left",779,518,1)
MouseClick("left",747,560,1)
Sleep(350)
_WinWaitActivate("試験開始!!","模擬テストを始めます。")
MouseClick("left",203,153,1)
Sleep(350)
_WinWaitActivate("MogiTester","Ctrl＋Enter：前の問題")
Send("seitou{SPACE}{ENTER}{ENTER}kokkai{SPACE}{ENTER}{ENTER}{DOWN}{DOWN}{ENTER}korenihansuru{SPACE}{ENTER}{F1}")
Sleep(350)
_WinWaitActivate("採点結果","正解率は")
Sleep(350)
Send("{LEFT}{ENTER}")
_WinWaitActivate("MogiTester","Ctrl＋Enter：前の問題")
Sleep(350)
MouseClick("left",988,9,1)
